# ==============================================================================
# IPsec / StrongSwan Tunnel Configuration (ipsec.conf)
# Nexis Core Platform Enterprise Gateway Testbed
# ==============================================================================
config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=yes

conn %default
    keyingtries=%forever
    dpddelay=30s
    dpdtimeout=120s
    dpdaction=restart

conn nexis-banking-tunnel
    authby=secret
    auto=start
    keyexchange=ikev1
    left=192.168.10.1
    leftid=@gateway.nexis.finance
    right=203.0.113.50
    rightid=@partner.bank.internal
    ike=aes256-sha1-modp1024,3des-md5-modp1024
    esp=3des-md5-modp1024!
